export const GET_AUTHORIZATION = "GET_AUTHORIZATION";
export const GET_ITEM_CHUNK = "GET_ITEM_CHUNCK";
export const GET_WEATHER_CHUNK = "GET_WEATHER_CHUNK";
export const UPDATE_LOADING_PROGRESS = "UPDATE_LOADING_PROGRESS";
export const SET_LOADING_STATE = "SET_LOADING_STATE";
